[package]
name = "sysmaster"
version = "0.2.2"
authors = ["sysmaster"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "sysmaster"
path = "src/sysmaster/main.rs"

[[bin]]
name = "pctrl"
path = "src/pctrl/main.rs"

[[bin]]
name = "init"
path = "src/init/main.rs"

[[bin]]
name = "fstab"
path = "src/fstab/main.rs"

[[bin]]
name = "random_seed"
path = "src/random_seed/main.rs"

[[bin]]
name = "sysmonitor"
path = "src/sysmonitor/main.rs"

[[bin]]
name = "rc-local-generator"
path = "src/rc-local-generator/main.rs"

[dependencies]
# internal libraries
libcgroup = { path = "libs/libcgroup" }
libevent = { path = "libs/libevent" }
libutils = { path = "libs/libutils" }
libsysmaster = { path = "libsysmaster" }

# third libraries
bitflags = "1.3.2"
clap = { version = "3.1.8", features = ["derive"] }
confique = { version = "0.1.3", default-features= false, features = [ 'toml' ] }
dynamic_reload = "0.4.0"
epoll = "4.3.1"
heed = "0.11.0"
http = "0.2" # 我们使用 HTTP status code 所以引入这个类型库
inotify = "0.10"
lazy_static = "1.4.0"
libc = "0.2.*"
libmount = "0.1.15"
log = "0.4"
nix = "0.24"
once_cell = { version = "1.5.2"}
procfs = "0.12.0"
prost = "0.9" # 处理 protobuf 的代码
regex = "1"
serde = "1.0.130"
serde_derive = "1.0.130"
signal-hook = "0.3.13"
signal-hook-registry = "1.4.0"
siphasher = { version = "0.3", features = ["serde"] }
strum = { version = "0.23", features = ["derive"] }
toml = "0.5.8"
walkdir = "2"
xattr = "0.2.3"

[build-dependencies]
prost-build = "0.9" # 编译 protobuf

[profile.dev]
panic = 'abort'

[profile.release]
panic = 'abort'

[workspace]
members = [
  "libsysmaster",
  "libs/libcgroup",
  "libs/libevent",
  "libs/libutils",
  "libs/libtests",
  "libs/libwatchdog",
  "coms/service",
  "coms/socket",
  "coms/target",
  "coms/mount",
]
