[package]
name = "process1"
version = "0.1.0"
authors = ["overweight <hexiaowen@huawei.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# crate_type = ["dylib"]
crate_type = ["lib"]
path = "src/lib.rs"
name = "process1"

[dependencies]
utils = { path = "../libutils" }
libevent = { path = "../libs/libevent" }
libcgroup = { path = "../libs/libcgroup" }

dynamic_reload = "0.8.0"
walkdir = "2"
siphasher = { version = "0.3", features = ["serde"] }

strum = { version = "0.23", features = ["derive"] }
nix = "0.24"
log = "0.4"
libc = "0.2.*"
signal-hook = "0.3.13"
prost = "0.9" # 处理 protobuf 的代码
http = "0.2" # 我们使用 HTTP status code 所以引入这个类型库
clap = { version = "3.1.8", features = ["derive"] }
once_cell = { version = "1.5.2"}
serde_derive = "1.0.130"
serde = "1.0.130"
toml = "0.5.8"
regex = "1"
bitflags = "1.3.2"
lazy_static = "1.4.0"
confique = { version = "0.1.3", default-features= false, features = [ 'toml' ] }
heed = "0.11.0"

[build-dependencies]
prost-build = "0.9" # 编译 protobuf

[dev-dependencies]
tests = { path = "../libs/libtests" }

[[example]]
name = "signals"
path = "./examples/signal.rs"
