[package]
name = "target"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
crate-type = ["dylib"]
name = "target"

[dependencies]
utils = { path = "../../libutils" }
libcgroup = { path = "../../libs/libcgroup" }
process1 = { path = "../../process1" }

dynamic_reload = "0.8.0"
strum = { version = "0.23", features = ["derive"] }
nix = "0.24"
log = "0.4"
toml = "0.5.8"
serde_derive = "1.0.130"
serde = "1.0.130"
once_cell = { version = "1.5.2"}
